export enum RoleType {
  PLN_ADMIN = 'ADMIN',
  PLN_SUPERADMIN = 'SUPERADMIN',
  PLN_VERIFICATOR = 'VERIFICATOR',
  PLN_SURVEYOR = 'SURVEYOR',
  PLN_AMPT = 'ASISTEN_MANAJER_PELAYANAN_TEKNIK',
  PLN_AMPP = 'ASISTEN_MANAJER_PELAYANAN_PELANGGAN',
  PLN_MUP3 = 'MANAGER_UNIT_PELAKSANA_PELAYANAN_PELANGGAN',
  OUTSOURCE_SURVEYOR = 'OUTSOURCE_SURVEYOR',
  MITRA_ADMIN = 'MITRA_ADMIN',
  PLN_ADMIN_ARSIP = 'ADMIN_ARSIP',
}
